services:
  php:
    build: .
    environment:
      SERVER_NAME: localhost
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:3306/${DB_NAME}?serverVersion=8.4.3&charset=utf8mb4
    working_dir: /var/www/html/public
    container_name: php
    volumes:
      - ./public:/var/www/html/public
      - ./App:/var/www/html/App
    ports:
      - '8080:80'
    depends_on:
      - mysql
  mysql:
    env_file:
      - .env
    ports:
      - '3306:3306'
    container_name: mysql
    image: mysql:8.4.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database_data:/var/lib/mysql
volumes:
  database_data: